uploads = []
generated = []

[[outputs]]
id = "OqKyUbsbr-HCWC1CZnsr3"
uri = "file://nagibe-app.tar.gz"
type = "unspecified"
title = "Nagibe Produção — Código Completo"

[[outputs]]
id = "UBMTGnjBn1v8HXAEjasN3"
uri = "file://backup.sql.gz"
type = "unspecified"
title = "Nagibe Produção — Backup SQL"
